/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.futurehotel.framework.dts.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CharacterT extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1775377444003683903L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Character\",\"namespace\":\"com.alibaba.dts.formats.avro\",\"fields\":[{\"name\":\"charset\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"value\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CharacterT> ENCODER =
      new BinaryMessageEncoder<CharacterT>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CharacterT> DECODER =
      new BinaryMessageDecoder<CharacterT>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<CharacterT> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<CharacterT> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CharacterT>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Character to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Character from a ByteBuffer. */
  public static CharacterT fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String charset;
  @Deprecated public java.nio.ByteBuffer value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CharacterT() {}

  /**
   * All-args constructor.
   * @param charset The new value for charset
   * @param value The new value for value
   */
  public CharacterT(java.lang.String charset, java.nio.ByteBuffer value) {
    this.charset = charset;
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return charset;
    case 1: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: charset = (java.lang.String)value$; break;
    case 1: value = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'charset' field.
   * @return The value of the 'charset' field.
   */
  public java.lang.String getCharset() {
    return charset;
  }

  /**
   * Sets the value of the 'charset' field.
   * @param value the value to set.
   */
  public void setCharset(java.lang.String value) {
    this.charset = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.nio.ByteBuffer getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.nio.ByteBuffer value) {
    this.value = value;
  }

  /**
   * Creates a new Character RecordBuilder.
   * @return A new Character RecordBuilder
   */
  public static CharacterT.Builder newBuilder() {
    return new CharacterT.Builder();
  }

  /**
   * Creates a new Character RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Character RecordBuilder
   */
  public static CharacterT.Builder newBuilder(CharacterT.Builder other) {
    return new CharacterT.Builder(other);
  }

  /**
   * Creates a new Character RecordBuilder by copying an existing Character instance.
   * @param other The existing instance to copy.
   * @return A new Character RecordBuilder
   */
  public static CharacterT.Builder newBuilder(CharacterT other) {
    return new CharacterT.Builder(other);
  }

  /**
   * RecordBuilder for Character instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CharacterT>
    implements org.apache.avro.data.RecordBuilder<CharacterT> {

    private java.lang.String charset;
    private java.nio.ByteBuffer value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(CharacterT.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.charset)) {
        this.charset = data().deepCopy(fields()[0].schema(), other.charset);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Character instance
     * @param other The existing instance to copy.
     */
    private Builder(CharacterT other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.charset)) {
        this.charset = data().deepCopy(fields()[0].schema(), other.charset);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'charset' field.
      * @return The value.
      */
    public java.lang.String getCharset() {
      return charset;
    }

    /**
      * Sets the value of the 'charset' field.
      * @param value The value of 'charset'.
      * @return This builder.
      */
    public CharacterT.Builder setCharset(java.lang.String value) {
      validate(fields()[0], value);
      this.charset = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'charset' field has been set.
      * @return True if the 'charset' field has been set, false otherwise.
      */
    public boolean hasCharset() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'charset' field.
      * @return This builder.
      */
    public CharacterT.Builder clearCharset() {
      charset = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public CharacterT.Builder setValue(java.nio.ByteBuffer value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public CharacterT.Builder clearValue() {
      value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CharacterT build() {
      try {
        CharacterT record = new CharacterT();
        record.charset = fieldSetFlags()[0] ? this.charset : (java.lang.String) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.nio.ByteBuffer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CharacterT>
    WRITER$ = (org.apache.avro.io.DatumWriter<CharacterT>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CharacterT>
    READER$ = (org.apache.avro.io.DatumReader<CharacterT>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
